site_name: P1sc3s007的个人博客
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - search.suggest
    - search.share
    - header.autohide
    - announce.dismiss
    - navigation.footer
  palette:
    primary: black
plugins:
  - search
  - blog
  - tags
extra:
  social:
    - icon: fontawesome/brands/bilibili 
      link: https://space.bilibili.com/40044305
      name: Bilibili
copyright: Copyright &copy; 2024 P1sc3s007
repo_url: https://github.com/Pisces032/Blog
repo_name: Pisces032/Blog
