site_name: P1sc3s007的个人博客
site_url: https://pisces032.github.io/P1sc3s007JustMyBlog/
site_author: P1sc3s007
site_description: P1sc3s007的个人网站

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - search.suggest
    - search.share
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.top
  palette:
    primary: black

plugins:
  - search

copyright: Copyright &copy; 2024 P1sc3s007
repo_url: https://github.com/Pisces032/Blog
repo_name: Pisces032/Blog

markdown_extensions:
  - toc:
      permalink: ⚓︎
      toc_depth: 3
  
extra:
  social:
    - icon: fontawesome/brands/bilibili 
      link: https://space.bilibili.com/40044305
      name: Bilibili
    - icon: fontawesome/brands/github
      link: https://github.com/Pisces032
      name: GitHub

nav: 
  - Welcome:
    - index.md
  - Blog: 
    - blog/index.md
    - blog/hello-world.md
    - 寄术: 
      - 提高代码可读性的不同命名方法: blog/tech/提高代码可读性的一些方法.md
      - Git使用: blog/tech/Git 使用.md
  - Programming: 
    - 1.21笔记: programming/move/Move 1.21.md
    #- programming/move/Move语言笔记.md
  - WP: 
    - wp/MoveCTF2024 checkin WP.md
  - Achieve: 
    - weekly: 
      - achieve/week/2023 12月第3周周报.md
      #- achieve/week/2023 12月第4周周报.md
      #- achieve/week/2023 12月第5周周报.md
    #- yearly: 
      #- 2023年度总结: achieve/year/2023年度总结.md